name: fitfat
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  video_player: ^2.4.7
  profile: ^0.0.1
  getwidget: ^3.0.1
  transparent_image_button: ^1.0.0
  animated_splash_screen:
  flutter_svg: ^1.1.6
  url_launcher: ^6.1.6
  firebase_core: ^2.1.1
  firebase_auth: ^4.1.1
  modal_progress_hud_nsn: ^0.3.0
  provider: ^6.0.4
  flutter_statusbarcolor_ns: ^0.5.0
  legacy_buttons: ^0.0.1
  flutter_bloc: ^8.1.1
  google_sign_in: ^5.4.2
  cloud_firestore: ^4.1.0
  flutter_profile_picture: ^2.0.0
  google_fonts: ^3.0.1
  animated_button_bar: ^0.0.2
  badges: ^2.0.3
  group_button: ^5.2.2
  grouped_buttons: ^1.0.4
  custom_radio_grouped_button: ^2.1.2+2
  crea_radio_button: ^0.6.0
  multiselect_formfield: ^0.1.7
  horizontal_card_pager: ^1.1.1
  horizontal_list: ^0.0.5
  flutter_horizontal_featured_list: ^1.0.1+1
  floating_bottom_navigation_bar: ^1.5.2
  pedometer: ^3.0.0
  shared_preferences: ^2.0.15
  google_nav_bar: ^5.0.6
  icony: ^1.0.5
  carousel_slider: ^4.2.1
  chewie: ^1.3.6
  image_picker: ^0.8.6
  health: ^4.4.0
  flutter_local_notifications: ^13.0.0
  sensors_plus: ^2.0.1
  nepali_utils: ^3.0.3
  percent_indicator: ^4.2.2
  font_awesome_flutter: ^10.3.0
  flutter_launcher_icons: ^0.11.0
  equatable: ^2.0.3
  shimmer_animation: ^2.1.0+1
  get: ^4.6.5
  geolocator: ^9.0.2
  path_provider: ^2.0.11
  sqflite: ^2.2.2
  stop_watch_timer: ^2.0.0
  permission_handler: ^10.2.0
  web_socket_channel: ^2.2.0
  circular_indicator: ^1.0.6
  flutter_background_service: ^2.4.6
  workmanager: ^0.5.1
  flutter_facebook_auth: ^5.0.7
  day_night_time_picker: ^1.1.5
  flutter_sensors: ^1.0.1
  awesome_notifications: ^0.7.4+1
  google_maps_flutter: ^2.2.5
  location: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/step.png"
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/videos/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR/NotoSansKR-Regular.otf
        - asset: assets/fonts/NotoSansKR/NotoSansKR-Bold.otf
        - asset: assets/fonts/Anton/Anton-Regular.ttf
          weight: 700
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
